locallibrary/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('books/', views.BookListView.as_view(), name='books'),
  path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
  path('authors/',views.AuthorListView.as_view(), name='authors'),
  path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
  path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
  path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
  path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
  path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
  path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += i18n_patterns(
#     path('pages/', include('django.contrib.flatpages.urls')),
#     path('accounts/', include('django.contrib.auth.urls')),
# )

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from datetime import date
import uuid # Required for unique book instances

# Create your models here.
class Genre(models.Model):
  """Model representing a book genre."""
  name = models.CharField(max_length=200, help_text=_('Enter a book genre (e.g.Science Fiction)'))
  def __str__(self):
    """String for representing the Model object."""
    return self.name
class Book(models.Model):
  """Model representing a book (but not a specific copy of a book)."""
  title = models.CharField(max_length=200)
  author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
  summary = models.TextField(max_length=1000, help_text=_('Enter a brief description of the book'))
  isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text=_('13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>'))

  genre = models.ManyToManyField(Genre, help_text=_('Select a genre for this book'))

  def __str__(self):
    """String for representing the Model object."""
    return self.title

  def get_absolute_url(self):
    """Returns the url to access a detail record for this book."""
    return reverse('book-detail', args=[str(self.id)])

  def display_genre(self):
    return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    @property
    def is_overdue(self):
      if self.due_back and date.today() > self.due_back:
        return True
      return False

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text=_('Unique ID for this particular book across whole library'))
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text= _('Book availability'),
    )

    class Meta:
      ordering = ['due_back']
      def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

      permissions = (("can_mark_returned", "Set book as returned"),)

class Author(models.Model):
  """Model representing an author."""
  first_name = models.CharField(max_length=100)
  last_name = models.CharField(max_length=100)
  date_of_birth = models.DateField(null=True, blank=True)
  date_of_death = models.DateField('Died', null=True, blank=True)
  class Meta:
    ordering = ['last_name', 'first_name']

  def get_absolute_url(self):
    """Returns the url to access a particular author instance."""
    return reverse('author-detail', args=[str(self.id)])

  def __str__(self):
    """String for representing the Model object."""
    return f'{self.last_name}, {self.first_name}'

locallibrary/catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime
from . import constants

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text=_("Enter a date between now and 4 weeks (default 3)."))

    def clean_renewal_date(self):
      data = self.cleaned_data['renewal_date']

      if data < datetime.date.today():
          raise ValidationError(_('Invalid date - renewal in past'))

      if data > datetime.date.today() + datetime.timedelta(weeks=constants.VALIDATE_WEEKS):
          raise ValidationError(_('Invalid date - renewal more than {0} weeks ahead'.format(constants.VALIDATE_WEEKS)))

      return data

locallibrary/catalog/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

import datetime

# Create your views here.

from .models import Book, Author, BookInstance, Genre
from . import constants
from catalog.forms import RenewBookForm

# Create your views here.
def index(request):
  """View function for home page of site."""

  # Generate counts of some of the main objects
  num_books = Book.objects.count()

  num_instances = BookInstance.objects.count()

  # Available books (status = 'a')
  num_instances_available = BookInstance.objects.filter(status__exact=constants.BOOK_STATUS_AVAILABLE).count()

  # The 'all()' is implied by default.
  num_authors = Author.objects.count()

  num_genres = Genre.objects.filter(name__exact= constants.GENRE_NAME).count()

  num_visits = request.session.get('num_visits', constants.NUM_VISITS_INITIAL)

  request.session['num_visits'] = num_visits + 1

  context = {
      'num_books': num_books,
      'num_instances': num_instances,
      'num_instances_available': num_instances_available,
      'num_authors': num_authors,
      'num_genres': num_genres,
      'num_visits': num_visits
  }

  # Render the HTML template index.html with the data in the context variable
  return render(request, 'index.html', context=context)

class BookListView(generic.ListView):
  model = Book
  paginate_by = constants.PAGINATE

class AuthorListView(generic.ListView):
  model = Author

class BookDetailView(generic.DetailView):
  model = Book

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context["book_genres"] = context["book"].genre.all()
    context["book_instances"] = context["book"].bookinstance_set.all()
    return context

class AuthorDetailView(generic.DetailView):
  model = Author

class LoanedBooksByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name ='catalog/bookinstance_list_borrowed_user.html'
    paginate_by = constants.PAGINATE

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
      form = RenewBookForm(request.POST)
      if form.is_valid():
        book_instance.due_back = form.cleaned_data['renewal_date']
        book_instance.save()

        return HttpResponseRedirect(reverse('my-borrowed'))
    else:
      proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=constants.PROPOSED_RENEWAL_WEEKS)
      form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
      'form': form,
      'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)

class AuthorCreate(CreateView):
  model = Author
  fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']
  initial = {'date_of_death': '11/06/2020'}

class AuthorUpdate(UpdateView):
  model = Author
  fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death']

class AuthorDelete(DeleteView):
  model = Author
  success_url = reverse_lazy('authors')

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Delete Author" %}</h1>

    <p>{% translate "Are you sure you want to delete the author:" %} {{ author }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete.">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Name:" %} {{ author.last_name }}</h1>
    <p><strong>{% translate "Date of birth:" %}</strong>{{ author.date_of_birth }}</p>
    <p><strong>{% translate "Date of death:" %}</strong> {{ author.date_of_deadth }}</p>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Author List" %}</h1>
    {% if author_list %}
        <ul>
            {% for author in author_list %}
                <li>
                    <a href="{{ author.get_absolute_url }}">{{ author.first_name }}</a> ({{ author.date_of_birth }})
                    - <a href="{% url 'author-update' author.id %}">Update</a>
                    - <a href="{% url 'author-delete' author.id %}">Delete</a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% translate "There are no author in the library." %}</p>
    {% endif %}

    <a href="{%url 'author-create'%}">{% translate "Create Author" %}</a>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Title:" %} {{ book.title }}</h1>
    <p><strong>{% translate "Author:" %}</strong> <a href="">{{ book.author }}</a></p>
    <p><strong>{% translate "Summary:" %}</strong> {{ book.summary }}</p>
    <p><strong>{% translate "ISBN:" %}</strong> {{ book.isbn }}</p>
    <p><strong>{% translate "Language:" %}</strong> {{ book.language }}</p>
    <p><strong>{% translate "Genre:" %}</strong> {{ book_genres|join:", " }}</p>

    <div class="book-detail">
        <h4>{% translate "Copies" %}</h4>
        {% for copy in book_instances %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
            {% if copy.status != 'a' %}
                <p><strong>{% translate "Due to be returned:" %}</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>{% translate "Imprint:" %}</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>{% translate "Id:" %}</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load i18n %}

{% block content %}
    <h1>{% translate "Book List" %}</h1>
    {% if book_list %}
        <ul>
            {% for book in book_list %}
                <li>
                    <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{ book.author }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% translate "There are no books in the library." %}</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Renew:" %} {{ book_instance.book.title }}</h1>
    <p>{% translate "Borrower:" %} {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>{% translate "Due date:" %} {{ book_instance.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
  <h1>{% translate "Borrowed books" %}</h1>

  {% if bookinstance_list %}
  <ul>
    {% for bookinst in bookinstance_list %}
    <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
      <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})
      - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
    </li>
    {% endfor %}
  </ul>

  {% else %}
    <p>{% translate "There are no books borrowed." %}</p>
  {% endif %}
{% endblock %}